/**
 *
 * $Id$
 */
package org.locationtech.geoff.layer.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;
import org.locationtech.geoff.style.Style;

/**
 * A sample validator interface for {@link org.locationtech.geoff.layer.Vector}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VectorValidator {
	boolean validate();

	boolean validateStyles(EMap<String, Style> value);

	boolean validateStyles(EList<Style> value);

}
