/**
 *
 * $Id$
 */
package org.locationtech.geoff.style.validation;

import org.locationtech.geoff.style.Fill;
import org.locationtech.geoff.style.Stroke;

/**
 * A sample validator interface for {@link org.locationtech.geoff.style.Circle}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CircleValidator {
	boolean validate();

	boolean validateRadius(double value);

	boolean validateFill(Fill value);

	boolean validateStroke(Stroke value);
}
