/**
 *
 * $Id$
 */
package org.locationtech.geoff.style.validation;

import org.eclipse.emf.common.util.EList;

import org.locationtech.geoff.Color;

/**
 * A sample validator interface for {@link org.locationtech.geoff.style.Stroke}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StrokeValidator {
	boolean validate();

	boolean validateColor(Color value);

	boolean validateLineCap(String value);

	boolean validateLineJoin(String value);

	boolean validateMiterLimit(Double value);

	boolean validateWidth(Double value);

	boolean validateLineDash(EList<Double> value);
}
