/**
 *
 * $Id$
 */
package org.locationtech.geoff.style.validation;

import org.locationtech.geoff.style.Fill;
import org.locationtech.geoff.style.Stroke;

/**
 * A sample validator interface for {@link org.locationtech.geoff.style.Text}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TextValidator {
	boolean validate();

	boolean validateFill(Fill value);

	boolean validateFont(String value);

	boolean validateOffsetX(double value);

	boolean validateOffsetY(double value);

	boolean validateRotation(Double value);

	boolean validateScale(Double value);

	boolean validateStroke(Stroke value);

	boolean validateText(String value);

	boolean validateTextAlign(String value);

	boolean validateTextBaseLine(String value);
}
