/**
 *
 * $Id$
 */
package org.locationtech.geoff.validation;

import org.eclipse.emf.common.util.EList;
import org.locationtech.geoff.style.Style;

/**
 * A sample validator interface for {@link java.util.HashMap}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StyleEntryValidator {
	boolean validate();

	boolean validateTypedKey(String value);

	boolean validateTypedValue(EList<Style> value);

	boolean validateTypedValue(Style value);

	boolean validateKey(String value);

	boolean validateValue(Style value);
}
